// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Image.proto

package project1pbversion.cmpe275.sjsu.protobuf;

public final class ImagePB {
  private ImagePB() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface RequestOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required .protobuf.Header header = 1;
    /**
     * <code>required .protobuf.Header header = 1;</code>
     */
    boolean hasHeader();
    /**
     * <code>required .protobuf.Header header = 1;</code>
     */
    project1pbversion.cmpe275.sjsu.protobuf.ImagePB.Header getHeader();
    /**
     * <code>required .protobuf.Header header = 1;</code>
     */
    project1pbversion.cmpe275.sjsu.protobuf.ImagePB.HeaderOrBuilder getHeaderOrBuilder();

    // required .protobuf.Payload body = 2;
    /**
     * <code>required .protobuf.Payload body = 2;</code>
     */
    boolean hasBody();
    /**
     * <code>required .protobuf.Payload body = 2;</code>
     */
    project1pbversion.cmpe275.sjsu.protobuf.ImagePB.Payload getBody();
    /**
     * <code>required .protobuf.Payload body = 2;</code>
     */
    project1pbversion.cmpe275.sjsu.protobuf.ImagePB.PayloadOrBuilder getBodyOrBuilder();
  }
  /**
   * Protobuf type {@code protobuf.Request}
   */
  public static final class Request extends
      com.google.protobuf.GeneratedMessage
      implements RequestOrBuilder {
    // Use Request.newBuilder() to construct.
    private Request(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Request(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Request defaultInstance;
    public static Request getDefaultInstance() {
      return defaultInstance;
    }

    public Request getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Request(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              project1pbversion.cmpe275.sjsu.protobuf.ImagePB.Header.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) == 0x00000001)) {
                subBuilder = header_.toBuilder();
              }
              header_ = input.readMessage(project1pbversion.cmpe275.sjsu.protobuf.ImagePB.Header.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(header_);
                header_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
            case 18: {
              project1pbversion.cmpe275.sjsu.protobuf.ImagePB.Payload.Builder subBuilder = null;
              if (((bitField0_ & 0x00000002) == 0x00000002)) {
                subBuilder = body_.toBuilder();
              }
              body_ = input.readMessage(project1pbversion.cmpe275.sjsu.protobuf.ImagePB.Payload.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(body_);
                body_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000002;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return project1pbversion.cmpe275.sjsu.protobuf.ImagePB.internal_static_protobuf_Request_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return project1pbversion.cmpe275.sjsu.protobuf.ImagePB.internal_static_protobuf_Request_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              project1pbversion.cmpe275.sjsu.protobuf.ImagePB.Request.class, project1pbversion.cmpe275.sjsu.protobuf.ImagePB.Request.Builder.class);
    }

    public static com.google.protobuf.Parser<Request> PARSER =
        new com.google.protobuf.AbstractParser<Request>() {
      public Request parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Request(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Request> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required .protobuf.Header header = 1;
    public static final int HEADER_FIELD_NUMBER = 1;
    private project1pbversion.cmpe275.sjsu.protobuf.ImagePB.Header header_;
    /**
     * <code>required .protobuf.Header header = 1;</code>
     */
    public boolean hasHeader() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .protobuf.Header header = 1;</code>
     */
    public project1pbversion.cmpe275.sjsu.protobuf.ImagePB.Header getHeader() {
      return header_;
    }
    /**
     * <code>required .protobuf.Header header = 1;</code>
     */
    public project1pbversion.cmpe275.sjsu.protobuf.ImagePB.HeaderOrBuilder getHeaderOrBuilder() {
      return header_;
    }

    // required .protobuf.Payload body = 2;
    public static final int BODY_FIELD_NUMBER = 2;
    private project1pbversion.cmpe275.sjsu.protobuf.ImagePB.Payload body_;
    /**
     * <code>required .protobuf.Payload body = 2;</code>
     */
    public boolean hasBody() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required .protobuf.Payload body = 2;</code>
     */
    public project1pbversion.cmpe275.sjsu.protobuf.ImagePB.Payload getBody() {
      return body_;
    }
    /**
     * <code>required .protobuf.Payload body = 2;</code>
     */
    public project1pbversion.cmpe275.sjsu.protobuf.ImagePB.PayloadOrBuilder getBodyOrBuilder() {
      return body_;
    }

    private void initFields() {
      header_ = project1pbversion.cmpe275.sjsu.protobuf.ImagePB.Header.getDefaultInstance();
      body_ = project1pbversion.cmpe275.sjsu.protobuf.ImagePB.Payload.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasHeader()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasBody()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, header_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(2, body_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, header_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, body_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static project1pbversion.cmpe275.sjsu.protobuf.ImagePB.Request parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static project1pbversion.cmpe275.sjsu.protobuf.ImagePB.Request parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static project1pbversion.cmpe275.sjsu.protobuf.ImagePB.Request parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static project1pbversion.cmpe275.sjsu.protobuf.ImagePB.Request parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static project1pbversion.cmpe275.sjsu.protobuf.ImagePB.Request parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static project1pbversion.cmpe275.sjsu.protobuf.ImagePB.Request parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static project1pbversion.cmpe275.sjsu.protobuf.ImagePB.Request parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static project1pbversion.cmpe275.sjsu.protobuf.ImagePB.Request parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static project1pbversion.cmpe275.sjsu.protobuf.ImagePB.Request parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static project1pbversion.cmpe275.sjsu.protobuf.ImagePB.Request parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(project1pbversion.cmpe275.sjsu.protobuf.ImagePB.Request prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protobuf.Request}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements project1pbversion.cmpe275.sjsu.protobuf.ImagePB.RequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return project1pbversion.cmpe275.sjsu.protobuf.ImagePB.internal_static_protobuf_Request_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return project1pbversion.cmpe275.sjsu.protobuf.ImagePB.internal_static_protobuf_Request_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                project1pbversion.cmpe275.sjsu.protobuf.ImagePB.Request.class, project1pbversion.cmpe275.sjsu.protobuf.ImagePB.Request.Builder.class);
      }

      // Construct using project1pbversion.cmpe275.sjsu.protobuf.ImagePB.Request.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getHeaderFieldBuilder();
          getBodyFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (headerBuilder_ == null) {
          header_ = project1pbversion.cmpe275.sjsu.protobuf.ImagePB.Header.getDefaultInstance();
        } else {
          headerBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        if (bodyBuilder_ == null) {
          body_ = project1pbversion.cmpe275.sjsu.protobuf.ImagePB.Payload.getDefaultInstance();
        } else {
          bodyBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return project1pbversion.cmpe275.sjsu.protobuf.ImagePB.internal_static_protobuf_Request_descriptor;
      }

      public project1pbversion.cmpe275.sjsu.protobuf.ImagePB.Request getDefaultInstanceForType() {
        return project1pbversion.cmpe275.sjsu.protobuf.ImagePB.Request.getDefaultInstance();
      }

      public project1pbversion.cmpe275.sjsu.protobuf.ImagePB.Request build() {
        project1pbversion.cmpe275.sjsu.protobuf.ImagePB.Request result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public project1pbversion.cmpe275.sjsu.protobuf.ImagePB.Request buildPartial() {
        project1pbversion.cmpe275.sjsu.protobuf.ImagePB.Request result = new project1pbversion.cmpe275.sjsu.protobuf.ImagePB.Request(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (headerBuilder_ == null) {
          result.header_ = header_;
        } else {
          result.header_ = headerBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        if (bodyBuilder_ == null) {
          result.body_ = body_;
        } else {
          result.body_ = bodyBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof project1pbversion.cmpe275.sjsu.protobuf.ImagePB.Request) {
          return mergeFrom((project1pbversion.cmpe275.sjsu.protobuf.ImagePB.Request)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(project1pbversion.cmpe275.sjsu.protobuf.ImagePB.Request other) {
        if (other == project1pbversion.cmpe275.sjsu.protobuf.ImagePB.Request.getDefaultInstance()) return this;
        if (other.hasHeader()) {
          mergeHeader(other.getHeader());
        }
        if (other.hasBody()) {
          mergeBody(other.getBody());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasHeader()) {
          
          return false;
        }
        if (!hasBody()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        project1pbversion.cmpe275.sjsu.protobuf.ImagePB.Request parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (project1pbversion.cmpe275.sjsu.protobuf.ImagePB.Request) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required .protobuf.Header header = 1;
      private project1pbversion.cmpe275.sjsu.protobuf.ImagePB.Header header_ = project1pbversion.cmpe275.sjsu.protobuf.ImagePB.Header.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          project1pbversion.cmpe275.sjsu.protobuf.ImagePB.Header, project1pbversion.cmpe275.sjsu.protobuf.ImagePB.Header.Builder, project1pbversion.cmpe275.sjsu.protobuf.ImagePB.HeaderOrBuilder> headerBuilder_;
      /**
       * <code>required .protobuf.Header header = 1;</code>
       */
      public boolean hasHeader() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .protobuf.Header header = 1;</code>
       */
      public project1pbversion.cmpe275.sjsu.protobuf.ImagePB.Header getHeader() {
        if (headerBuilder_ == null) {
          return header_;
        } else {
          return headerBuilder_.getMessage();
        }
      }
      /**
       * <code>required .protobuf.Header header = 1;</code>
       */
      public Builder setHeader(project1pbversion.cmpe275.sjsu.protobuf.ImagePB.Header value) {
        if (headerBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          header_ = value;
          onChanged();
        } else {
          headerBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .protobuf.Header header = 1;</code>
       */
      public Builder setHeader(
          project1pbversion.cmpe275.sjsu.protobuf.ImagePB.Header.Builder builderForValue) {
        if (headerBuilder_ == null) {
          header_ = builderForValue.build();
          onChanged();
        } else {
          headerBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .protobuf.Header header = 1;</code>
       */
      public Builder mergeHeader(project1pbversion.cmpe275.sjsu.protobuf.ImagePB.Header value) {
        if (headerBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              header_ != project1pbversion.cmpe275.sjsu.protobuf.ImagePB.Header.getDefaultInstance()) {
            header_ =
              project1pbversion.cmpe275.sjsu.protobuf.ImagePB.Header.newBuilder(header_).mergeFrom(value).buildPartial();
          } else {
            header_ = value;
          }
          onChanged();
        } else {
          headerBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .protobuf.Header header = 1;</code>
       */
      public Builder clearHeader() {
        if (headerBuilder_ == null) {
          header_ = project1pbversion.cmpe275.sjsu.protobuf.ImagePB.Header.getDefaultInstance();
          onChanged();
        } else {
          headerBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <code>required .protobuf.Header header = 1;</code>
       */
      public project1pbversion.cmpe275.sjsu.protobuf.ImagePB.Header.Builder getHeaderBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getHeaderFieldBuilder().getBuilder();
      }
      /**
       * <code>required .protobuf.Header header = 1;</code>
       */
      public project1pbversion.cmpe275.sjsu.protobuf.ImagePB.HeaderOrBuilder getHeaderOrBuilder() {
        if (headerBuilder_ != null) {
          return headerBuilder_.getMessageOrBuilder();
        } else {
          return header_;
        }
      }
      /**
       * <code>required .protobuf.Header header = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          project1pbversion.cmpe275.sjsu.protobuf.ImagePB.Header, project1pbversion.cmpe275.sjsu.protobuf.ImagePB.Header.Builder, project1pbversion.cmpe275.sjsu.protobuf.ImagePB.HeaderOrBuilder> 
          getHeaderFieldBuilder() {
        if (headerBuilder_ == null) {
          headerBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              project1pbversion.cmpe275.sjsu.protobuf.ImagePB.Header, project1pbversion.cmpe275.sjsu.protobuf.ImagePB.Header.Builder, project1pbversion.cmpe275.sjsu.protobuf.ImagePB.HeaderOrBuilder>(
                  header_,
                  getParentForChildren(),
                  isClean());
          header_ = null;
        }
        return headerBuilder_;
      }

      // required .protobuf.Payload body = 2;
      private project1pbversion.cmpe275.sjsu.protobuf.ImagePB.Payload body_ = project1pbversion.cmpe275.sjsu.protobuf.ImagePB.Payload.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          project1pbversion.cmpe275.sjsu.protobuf.ImagePB.Payload, project1pbversion.cmpe275.sjsu.protobuf.ImagePB.Payload.Builder, project1pbversion.cmpe275.sjsu.protobuf.ImagePB.PayloadOrBuilder> bodyBuilder_;
      /**
       * <code>required .protobuf.Payload body = 2;</code>
       */
      public boolean hasBody() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required .protobuf.Payload body = 2;</code>
       */
      public project1pbversion.cmpe275.sjsu.protobuf.ImagePB.Payload getBody() {
        if (bodyBuilder_ == null) {
          return body_;
        } else {
          return bodyBuilder_.getMessage();
        }
      }
      /**
       * <code>required .protobuf.Payload body = 2;</code>
       */
      public Builder setBody(project1pbversion.cmpe275.sjsu.protobuf.ImagePB.Payload value) {
        if (bodyBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          body_ = value;
          onChanged();
        } else {
          bodyBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>required .protobuf.Payload body = 2;</code>
       */
      public Builder setBody(
          project1pbversion.cmpe275.sjsu.protobuf.ImagePB.Payload.Builder builderForValue) {
        if (bodyBuilder_ == null) {
          body_ = builderForValue.build();
          onChanged();
        } else {
          bodyBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>required .protobuf.Payload body = 2;</code>
       */
      public Builder mergeBody(project1pbversion.cmpe275.sjsu.protobuf.ImagePB.Payload value) {
        if (bodyBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              body_ != project1pbversion.cmpe275.sjsu.protobuf.ImagePB.Payload.getDefaultInstance()) {
            body_ =
              project1pbversion.cmpe275.sjsu.protobuf.ImagePB.Payload.newBuilder(body_).mergeFrom(value).buildPartial();
          } else {
            body_ = value;
          }
          onChanged();
        } else {
          bodyBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>required .protobuf.Payload body = 2;</code>
       */
      public Builder clearBody() {
        if (bodyBuilder_ == null) {
          body_ = project1pbversion.cmpe275.sjsu.protobuf.ImagePB.Payload.getDefaultInstance();
          onChanged();
        } else {
          bodyBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      /**
       * <code>required .protobuf.Payload body = 2;</code>
       */
      public project1pbversion.cmpe275.sjsu.protobuf.ImagePB.Payload.Builder getBodyBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getBodyFieldBuilder().getBuilder();
      }
      /**
       * <code>required .protobuf.Payload body = 2;</code>
       */
      public project1pbversion.cmpe275.sjsu.protobuf.ImagePB.PayloadOrBuilder getBodyOrBuilder() {
        if (bodyBuilder_ != null) {
          return bodyBuilder_.getMessageOrBuilder();
        } else {
          return body_;
        }
      }
      /**
       * <code>required .protobuf.Payload body = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          project1pbversion.cmpe275.sjsu.protobuf.ImagePB.Payload, project1pbversion.cmpe275.sjsu.protobuf.ImagePB.Payload.Builder, project1pbversion.cmpe275.sjsu.protobuf.ImagePB.PayloadOrBuilder> 
          getBodyFieldBuilder() {
        if (bodyBuilder_ == null) {
          bodyBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              project1pbversion.cmpe275.sjsu.protobuf.ImagePB.Payload, project1pbversion.cmpe275.sjsu.protobuf.ImagePB.Payload.Builder, project1pbversion.cmpe275.sjsu.protobuf.ImagePB.PayloadOrBuilder>(
                  body_,
                  getParentForChildren(),
                  isClean());
          body_ = null;
        }
        return bodyBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:protobuf.Request)
    }

    static {
      defaultInstance = new Request(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:protobuf.Request)
  }

  public interface HeaderOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional .protobuf.Header.RequestType requestType = 1 [default = read];
    /**
     * <code>optional .protobuf.Header.RequestType requestType = 1 [default = read];</code>
     */
    boolean hasRequestType();
    /**
     * <code>optional .protobuf.Header.RequestType requestType = 1 [default = read];</code>
     */
    project1pbversion.cmpe275.sjsu.protobuf.ImagePB.Header.RequestType getRequestType();

    // optional .protobuf.Header.ResponseFlag responseFlag = 2 [default = success];
    /**
     * <code>optional .protobuf.Header.ResponseFlag responseFlag = 2 [default = success];</code>
     */
    boolean hasResponseFlag();
    /**
     * <code>optional .protobuf.Header.ResponseFlag responseFlag = 2 [default = success];</code>
     */
    project1pbversion.cmpe275.sjsu.protobuf.ImagePB.Header.ResponseFlag getResponseFlag();

    // optional int64 lastModified = 3;
    /**
     * <code>optional int64 lastModified = 3;</code>
     *
     * <pre>
     * Unix timestamp
     * </pre>
     */
    boolean hasLastModified();
    /**
     * <code>optional int64 lastModified = 3;</code>
     *
     * <pre>
     * Unix timestamp
     * </pre>
     */
    long getLastModified();

    // optional int32 contentLength = 4;
    /**
     * <code>optional int32 contentLength = 4;</code>
     */
    boolean hasContentLength();
    /**
     * <code>optional int32 contentLength = 4;</code>
     */
    int getContentLength();
  }
  /**
   * Protobuf type {@code protobuf.Header}
   */
  public static final class Header extends
      com.google.protobuf.GeneratedMessage
      implements HeaderOrBuilder {
    // Use Header.newBuilder() to construct.
    private Header(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Header(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Header defaultInstance;
    public static Header getDefaultInstance() {
      return defaultInstance;
    }

    public Header getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Header(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              project1pbversion.cmpe275.sjsu.protobuf.ImagePB.Header.RequestType value = project1pbversion.cmpe275.sjsu.protobuf.ImagePB.Header.RequestType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                requestType_ = value;
              }
              break;
            }
            case 16: {
              int rawValue = input.readEnum();
              project1pbversion.cmpe275.sjsu.protobuf.ImagePB.Header.ResponseFlag value = project1pbversion.cmpe275.sjsu.protobuf.ImagePB.Header.ResponseFlag.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(2, rawValue);
              } else {
                bitField0_ |= 0x00000002;
                responseFlag_ = value;
              }
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              lastModified_ = input.readInt64();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              contentLength_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return project1pbversion.cmpe275.sjsu.protobuf.ImagePB.internal_static_protobuf_Header_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return project1pbversion.cmpe275.sjsu.protobuf.ImagePB.internal_static_protobuf_Header_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              project1pbversion.cmpe275.sjsu.protobuf.ImagePB.Header.class, project1pbversion.cmpe275.sjsu.protobuf.ImagePB.Header.Builder.class);
    }

    public static com.google.protobuf.Parser<Header> PARSER =
        new com.google.protobuf.AbstractParser<Header>() {
      public Header parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Header(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Header> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code protobuf.Header.RequestType}
     */
    public enum RequestType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>read = 0;</code>
       */
      read(0, 0),
      /**
       * <code>write = 1;</code>
       */
      write(1, 1),
      /**
       * <code>delete = 2;</code>
       */
      delete(2, 2),
      ;

      /**
       * <code>read = 0;</code>
       */
      public static final int read_VALUE = 0;
      /**
       * <code>write = 1;</code>
       */
      public static final int write_VALUE = 1;
      /**
       * <code>delete = 2;</code>
       */
      public static final int delete_VALUE = 2;


      public final int getNumber() { return value; }

      public static RequestType valueOf(int value) {
        switch (value) {
          case 0: return read;
          case 1: return write;
          case 2: return delete;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<RequestType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<RequestType>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<RequestType>() {
              public RequestType findValueByNumber(int number) {
                return RequestType.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return project1pbversion.cmpe275.sjsu.protobuf.ImagePB.Header.getDescriptor().getEnumTypes().get(0);
      }

      private static final RequestType[] VALUES = values();

      public static RequestType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private RequestType(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:protobuf.Header.RequestType)
    }

    /**
     * Protobuf enum {@code protobuf.Header.ResponseFlag}
     */
    public enum ResponseFlag
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>success = 0;</code>
       */
      success(0, 0),
      /**
       * <code>failure = 1;</code>
       */
      failure(1, 1),
      ;

      /**
       * <code>success = 0;</code>
       */
      public static final int success_VALUE = 0;
      /**
       * <code>failure = 1;</code>
       */
      public static final int failure_VALUE = 1;


      public final int getNumber() { return value; }

      public static ResponseFlag valueOf(int value) {
        switch (value) {
          case 0: return success;
          case 1: return failure;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<ResponseFlag>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<ResponseFlag>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<ResponseFlag>() {
              public ResponseFlag findValueByNumber(int number) {
                return ResponseFlag.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return project1pbversion.cmpe275.sjsu.protobuf.ImagePB.Header.getDescriptor().getEnumTypes().get(1);
      }

      private static final ResponseFlag[] VALUES = values();

      public static ResponseFlag valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private ResponseFlag(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:protobuf.Header.ResponseFlag)
    }

    private int bitField0_;
    // optional .protobuf.Header.RequestType requestType = 1 [default = read];
    public static final int REQUESTTYPE_FIELD_NUMBER = 1;
    private project1pbversion.cmpe275.sjsu.protobuf.ImagePB.Header.RequestType requestType_;
    /**
     * <code>optional .protobuf.Header.RequestType requestType = 1 [default = read];</code>
     */
    public boolean hasRequestType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional .protobuf.Header.RequestType requestType = 1 [default = read];</code>
     */
    public project1pbversion.cmpe275.sjsu.protobuf.ImagePB.Header.RequestType getRequestType() {
      return requestType_;
    }

    // optional .protobuf.Header.ResponseFlag responseFlag = 2 [default = success];
    public static final int RESPONSEFLAG_FIELD_NUMBER = 2;
    private project1pbversion.cmpe275.sjsu.protobuf.ImagePB.Header.ResponseFlag responseFlag_;
    /**
     * <code>optional .protobuf.Header.ResponseFlag responseFlag = 2 [default = success];</code>
     */
    public boolean hasResponseFlag() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional .protobuf.Header.ResponseFlag responseFlag = 2 [default = success];</code>
     */
    public project1pbversion.cmpe275.sjsu.protobuf.ImagePB.Header.ResponseFlag getResponseFlag() {
      return responseFlag_;
    }

    // optional int64 lastModified = 3;
    public static final int LASTMODIFIED_FIELD_NUMBER = 3;
    private long lastModified_;
    /**
     * <code>optional int64 lastModified = 3;</code>
     *
     * <pre>
     * Unix timestamp
     * </pre>
     */
    public boolean hasLastModified() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int64 lastModified = 3;</code>
     *
     * <pre>
     * Unix timestamp
     * </pre>
     */
    public long getLastModified() {
      return lastModified_;
    }

    // optional int32 contentLength = 4;
    public static final int CONTENTLENGTH_FIELD_NUMBER = 4;
    private int contentLength_;
    /**
     * <code>optional int32 contentLength = 4;</code>
     */
    public boolean hasContentLength() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional int32 contentLength = 4;</code>
     */
    public int getContentLength() {
      return contentLength_;
    }

    private void initFields() {
      requestType_ = project1pbversion.cmpe275.sjsu.protobuf.ImagePB.Header.RequestType.read;
      responseFlag_ = project1pbversion.cmpe275.sjsu.protobuf.ImagePB.Header.ResponseFlag.success;
      lastModified_ = 0L;
      contentLength_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, requestType_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeEnum(2, responseFlag_.getNumber());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt64(3, lastModified_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, contentLength_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, requestType_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, responseFlag_.getNumber());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, lastModified_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, contentLength_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static project1pbversion.cmpe275.sjsu.protobuf.ImagePB.Header parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static project1pbversion.cmpe275.sjsu.protobuf.ImagePB.Header parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static project1pbversion.cmpe275.sjsu.protobuf.ImagePB.Header parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static project1pbversion.cmpe275.sjsu.protobuf.ImagePB.Header parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static project1pbversion.cmpe275.sjsu.protobuf.ImagePB.Header parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static project1pbversion.cmpe275.sjsu.protobuf.ImagePB.Header parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static project1pbversion.cmpe275.sjsu.protobuf.ImagePB.Header parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static project1pbversion.cmpe275.sjsu.protobuf.ImagePB.Header parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static project1pbversion.cmpe275.sjsu.protobuf.ImagePB.Header parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static project1pbversion.cmpe275.sjsu.protobuf.ImagePB.Header parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(project1pbversion.cmpe275.sjsu.protobuf.ImagePB.Header prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protobuf.Header}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements project1pbversion.cmpe275.sjsu.protobuf.ImagePB.HeaderOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return project1pbversion.cmpe275.sjsu.protobuf.ImagePB.internal_static_protobuf_Header_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return project1pbversion.cmpe275.sjsu.protobuf.ImagePB.internal_static_protobuf_Header_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                project1pbversion.cmpe275.sjsu.protobuf.ImagePB.Header.class, project1pbversion.cmpe275.sjsu.protobuf.ImagePB.Header.Builder.class);
      }

      // Construct using project1pbversion.cmpe275.sjsu.protobuf.ImagePB.Header.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        requestType_ = project1pbversion.cmpe275.sjsu.protobuf.ImagePB.Header.RequestType.read;
        bitField0_ = (bitField0_ & ~0x00000001);
        responseFlag_ = project1pbversion.cmpe275.sjsu.protobuf.ImagePB.Header.ResponseFlag.success;
        bitField0_ = (bitField0_ & ~0x00000002);
        lastModified_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000004);
        contentLength_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return project1pbversion.cmpe275.sjsu.protobuf.ImagePB.internal_static_protobuf_Header_descriptor;
      }

      public project1pbversion.cmpe275.sjsu.protobuf.ImagePB.Header getDefaultInstanceForType() {
        return project1pbversion.cmpe275.sjsu.protobuf.ImagePB.Header.getDefaultInstance();
      }

      public project1pbversion.cmpe275.sjsu.protobuf.ImagePB.Header build() {
        project1pbversion.cmpe275.sjsu.protobuf.ImagePB.Header result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public project1pbversion.cmpe275.sjsu.protobuf.ImagePB.Header buildPartial() {
        project1pbversion.cmpe275.sjsu.protobuf.ImagePB.Header result = new project1pbversion.cmpe275.sjsu.protobuf.ImagePB.Header(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.requestType_ = requestType_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.responseFlag_ = responseFlag_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.lastModified_ = lastModified_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.contentLength_ = contentLength_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof project1pbversion.cmpe275.sjsu.protobuf.ImagePB.Header) {
          return mergeFrom((project1pbversion.cmpe275.sjsu.protobuf.ImagePB.Header)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(project1pbversion.cmpe275.sjsu.protobuf.ImagePB.Header other) {
        if (other == project1pbversion.cmpe275.sjsu.protobuf.ImagePB.Header.getDefaultInstance()) return this;
        if (other.hasRequestType()) {
          setRequestType(other.getRequestType());
        }
        if (other.hasResponseFlag()) {
          setResponseFlag(other.getResponseFlag());
        }
        if (other.hasLastModified()) {
          setLastModified(other.getLastModified());
        }
        if (other.hasContentLength()) {
          setContentLength(other.getContentLength());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        project1pbversion.cmpe275.sjsu.protobuf.ImagePB.Header parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (project1pbversion.cmpe275.sjsu.protobuf.ImagePB.Header) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional .protobuf.Header.RequestType requestType = 1 [default = read];
      private project1pbversion.cmpe275.sjsu.protobuf.ImagePB.Header.RequestType requestType_ = project1pbversion.cmpe275.sjsu.protobuf.ImagePB.Header.RequestType.read;
      /**
       * <code>optional .protobuf.Header.RequestType requestType = 1 [default = read];</code>
       */
      public boolean hasRequestType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional .protobuf.Header.RequestType requestType = 1 [default = read];</code>
       */
      public project1pbversion.cmpe275.sjsu.protobuf.ImagePB.Header.RequestType getRequestType() {
        return requestType_;
      }
      /**
       * <code>optional .protobuf.Header.RequestType requestType = 1 [default = read];</code>
       */
      public Builder setRequestType(project1pbversion.cmpe275.sjsu.protobuf.ImagePB.Header.RequestType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        requestType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .protobuf.Header.RequestType requestType = 1 [default = read];</code>
       */
      public Builder clearRequestType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        requestType_ = project1pbversion.cmpe275.sjsu.protobuf.ImagePB.Header.RequestType.read;
        onChanged();
        return this;
      }

      // optional .protobuf.Header.ResponseFlag responseFlag = 2 [default = success];
      private project1pbversion.cmpe275.sjsu.protobuf.ImagePB.Header.ResponseFlag responseFlag_ = project1pbversion.cmpe275.sjsu.protobuf.ImagePB.Header.ResponseFlag.success;
      /**
       * <code>optional .protobuf.Header.ResponseFlag responseFlag = 2 [default = success];</code>
       */
      public boolean hasResponseFlag() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional .protobuf.Header.ResponseFlag responseFlag = 2 [default = success];</code>
       */
      public project1pbversion.cmpe275.sjsu.protobuf.ImagePB.Header.ResponseFlag getResponseFlag() {
        return responseFlag_;
      }
      /**
       * <code>optional .protobuf.Header.ResponseFlag responseFlag = 2 [default = success];</code>
       */
      public Builder setResponseFlag(project1pbversion.cmpe275.sjsu.protobuf.ImagePB.Header.ResponseFlag value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        responseFlag_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .protobuf.Header.ResponseFlag responseFlag = 2 [default = success];</code>
       */
      public Builder clearResponseFlag() {
        bitField0_ = (bitField0_ & ~0x00000002);
        responseFlag_ = project1pbversion.cmpe275.sjsu.protobuf.ImagePB.Header.ResponseFlag.success;
        onChanged();
        return this;
      }

      // optional int64 lastModified = 3;
      private long lastModified_ ;
      /**
       * <code>optional int64 lastModified = 3;</code>
       *
       * <pre>
       * Unix timestamp
       * </pre>
       */
      public boolean hasLastModified() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int64 lastModified = 3;</code>
       *
       * <pre>
       * Unix timestamp
       * </pre>
       */
      public long getLastModified() {
        return lastModified_;
      }
      /**
       * <code>optional int64 lastModified = 3;</code>
       *
       * <pre>
       * Unix timestamp
       * </pre>
       */
      public Builder setLastModified(long value) {
        bitField0_ |= 0x00000004;
        lastModified_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 lastModified = 3;</code>
       *
       * <pre>
       * Unix timestamp
       * </pre>
       */
      public Builder clearLastModified() {
        bitField0_ = (bitField0_ & ~0x00000004);
        lastModified_ = 0L;
        onChanged();
        return this;
      }

      // optional int32 contentLength = 4;
      private int contentLength_ ;
      /**
       * <code>optional int32 contentLength = 4;</code>
       */
      public boolean hasContentLength() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional int32 contentLength = 4;</code>
       */
      public int getContentLength() {
        return contentLength_;
      }
      /**
       * <code>optional int32 contentLength = 4;</code>
       */
      public Builder setContentLength(int value) {
        bitField0_ |= 0x00000008;
        contentLength_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 contentLength = 4;</code>
       */
      public Builder clearContentLength() {
        bitField0_ = (bitField0_ & ~0x00000008);
        contentLength_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:protobuf.Header)
    }

    static {
      defaultInstance = new Header(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:protobuf.Header)
  }

  public interface PayloadOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional string uuid = 1;
    /**
     * <code>optional string uuid = 1;</code>
     *
     * <pre>
     * Required for types 0 &amp; 2
     * </pre>
     */
    boolean hasUuid();
    /**
     * <code>optional string uuid = 1;</code>
     *
     * <pre>
     * Required for types 0 &amp; 2
     * </pre>
     */
    java.lang.String getUuid();
    /**
     * <code>optional string uuid = 1;</code>
     *
     * <pre>
     * Required for types 0 &amp; 2
     * </pre>
     */
    com.google.protobuf.ByteString
        getUuidBytes();

    // optional string name = 2;
    /**
     * <code>optional string name = 2;</code>
     *
     * <pre>
     * Required for type 1
     * </pre>
     */
    boolean hasName();
    /**
     * <code>optional string name = 2;</code>
     *
     * <pre>
     * Required for type 1
     * </pre>
     */
    java.lang.String getName();
    /**
     * <code>optional string name = 2;</code>
     *
     * <pre>
     * Required for type 1
     * </pre>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    // optional bytes data = 3;
    /**
     * <code>optional bytes data = 3;</code>
     *
     * <pre>
     * Required for type 1
     * </pre>
     */
    boolean hasData();
    /**
     * <code>optional bytes data = 3;</code>
     *
     * <pre>
     * Required for type 1
     * </pre>
     */
    com.google.protobuf.ByteString getData();
  }
  /**
   * Protobuf type {@code protobuf.Payload}
   */
  public static final class Payload extends
      com.google.protobuf.GeneratedMessage
      implements PayloadOrBuilder {
    // Use Payload.newBuilder() to construct.
    private Payload(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Payload(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Payload defaultInstance;
    public static Payload getDefaultInstance() {
      return defaultInstance;
    }

    public Payload getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Payload(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              uuid_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              name_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              data_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return project1pbversion.cmpe275.sjsu.protobuf.ImagePB.internal_static_protobuf_Payload_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return project1pbversion.cmpe275.sjsu.protobuf.ImagePB.internal_static_protobuf_Payload_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              project1pbversion.cmpe275.sjsu.protobuf.ImagePB.Payload.class, project1pbversion.cmpe275.sjsu.protobuf.ImagePB.Payload.Builder.class);
    }

    public static com.google.protobuf.Parser<Payload> PARSER =
        new com.google.protobuf.AbstractParser<Payload>() {
      public Payload parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Payload(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Payload> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional string uuid = 1;
    public static final int UUID_FIELD_NUMBER = 1;
    private java.lang.Object uuid_;
    /**
     * <code>optional string uuid = 1;</code>
     *
     * <pre>
     * Required for types 0 &amp; 2
     * </pre>
     */
    public boolean hasUuid() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string uuid = 1;</code>
     *
     * <pre>
     * Required for types 0 &amp; 2
     * </pre>
     */
    public java.lang.String getUuid() {
      java.lang.Object ref = uuid_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          uuid_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string uuid = 1;</code>
     *
     * <pre>
     * Required for types 0 &amp; 2
     * </pre>
     */
    public com.google.protobuf.ByteString
        getUuidBytes() {
      java.lang.Object ref = uuid_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        uuid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string name = 2;
    public static final int NAME_FIELD_NUMBER = 2;
    private java.lang.Object name_;
    /**
     * <code>optional string name = 2;</code>
     *
     * <pre>
     * Required for type 1
     * </pre>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string name = 2;</code>
     *
     * <pre>
     * Required for type 1
     * </pre>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string name = 2;</code>
     *
     * <pre>
     * Required for type 1
     * </pre>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional bytes data = 3;
    public static final int DATA_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString data_;
    /**
     * <code>optional bytes data = 3;</code>
     *
     * <pre>
     * Required for type 1
     * </pre>
     */
    public boolean hasData() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional bytes data = 3;</code>
     *
     * <pre>
     * Required for type 1
     * </pre>
     */
    public com.google.protobuf.ByteString getData() {
      return data_;
    }

    private void initFields() {
      uuid_ = "";
      name_ = "";
      data_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getUuidBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, data_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getUuidBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, data_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static project1pbversion.cmpe275.sjsu.protobuf.ImagePB.Payload parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static project1pbversion.cmpe275.sjsu.protobuf.ImagePB.Payload parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static project1pbversion.cmpe275.sjsu.protobuf.ImagePB.Payload parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static project1pbversion.cmpe275.sjsu.protobuf.ImagePB.Payload parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static project1pbversion.cmpe275.sjsu.protobuf.ImagePB.Payload parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static project1pbversion.cmpe275.sjsu.protobuf.ImagePB.Payload parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static project1pbversion.cmpe275.sjsu.protobuf.ImagePB.Payload parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static project1pbversion.cmpe275.sjsu.protobuf.ImagePB.Payload parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static project1pbversion.cmpe275.sjsu.protobuf.ImagePB.Payload parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static project1pbversion.cmpe275.sjsu.protobuf.ImagePB.Payload parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(project1pbversion.cmpe275.sjsu.protobuf.ImagePB.Payload prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protobuf.Payload}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements project1pbversion.cmpe275.sjsu.protobuf.ImagePB.PayloadOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return project1pbversion.cmpe275.sjsu.protobuf.ImagePB.internal_static_protobuf_Payload_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return project1pbversion.cmpe275.sjsu.protobuf.ImagePB.internal_static_protobuf_Payload_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                project1pbversion.cmpe275.sjsu.protobuf.ImagePB.Payload.class, project1pbversion.cmpe275.sjsu.protobuf.ImagePB.Payload.Builder.class);
      }

      // Construct using project1pbversion.cmpe275.sjsu.protobuf.ImagePB.Payload.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        uuid_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        data_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return project1pbversion.cmpe275.sjsu.protobuf.ImagePB.internal_static_protobuf_Payload_descriptor;
      }

      public project1pbversion.cmpe275.sjsu.protobuf.ImagePB.Payload getDefaultInstanceForType() {
        return project1pbversion.cmpe275.sjsu.protobuf.ImagePB.Payload.getDefaultInstance();
      }

      public project1pbversion.cmpe275.sjsu.protobuf.ImagePB.Payload build() {
        project1pbversion.cmpe275.sjsu.protobuf.ImagePB.Payload result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public project1pbversion.cmpe275.sjsu.protobuf.ImagePB.Payload buildPartial() {
        project1pbversion.cmpe275.sjsu.protobuf.ImagePB.Payload result = new project1pbversion.cmpe275.sjsu.protobuf.ImagePB.Payload(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.uuid_ = uuid_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.data_ = data_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof project1pbversion.cmpe275.sjsu.protobuf.ImagePB.Payload) {
          return mergeFrom((project1pbversion.cmpe275.sjsu.protobuf.ImagePB.Payload)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(project1pbversion.cmpe275.sjsu.protobuf.ImagePB.Payload other) {
        if (other == project1pbversion.cmpe275.sjsu.protobuf.ImagePB.Payload.getDefaultInstance()) return this;
        if (other.hasUuid()) {
          bitField0_ |= 0x00000001;
          uuid_ = other.uuid_;
          onChanged();
        }
        if (other.hasName()) {
          bitField0_ |= 0x00000002;
          name_ = other.name_;
          onChanged();
        }
        if (other.hasData()) {
          setData(other.getData());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        project1pbversion.cmpe275.sjsu.protobuf.ImagePB.Payload parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (project1pbversion.cmpe275.sjsu.protobuf.ImagePB.Payload) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional string uuid = 1;
      private java.lang.Object uuid_ = "";
      /**
       * <code>optional string uuid = 1;</code>
       *
       * <pre>
       * Required for types 0 &amp; 2
       * </pre>
       */
      public boolean hasUuid() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string uuid = 1;</code>
       *
       * <pre>
       * Required for types 0 &amp; 2
       * </pre>
       */
      public java.lang.String getUuid() {
        java.lang.Object ref = uuid_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          uuid_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string uuid = 1;</code>
       *
       * <pre>
       * Required for types 0 &amp; 2
       * </pre>
       */
      public com.google.protobuf.ByteString
          getUuidBytes() {
        java.lang.Object ref = uuid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          uuid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string uuid = 1;</code>
       *
       * <pre>
       * Required for types 0 &amp; 2
       * </pre>
       */
      public Builder setUuid(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        uuid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string uuid = 1;</code>
       *
       * <pre>
       * Required for types 0 &amp; 2
       * </pre>
       */
      public Builder clearUuid() {
        bitField0_ = (bitField0_ & ~0x00000001);
        uuid_ = getDefaultInstance().getUuid();
        onChanged();
        return this;
      }
      /**
       * <code>optional string uuid = 1;</code>
       *
       * <pre>
       * Required for types 0 &amp; 2
       * </pre>
       */
      public Builder setUuidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        uuid_ = value;
        onChanged();
        return this;
      }

      // optional string name = 2;
      private java.lang.Object name_ = "";
      /**
       * <code>optional string name = 2;</code>
       *
       * <pre>
       * Required for type 1
       * </pre>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string name = 2;</code>
       *
       * <pre>
       * Required for type 1
       * </pre>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string name = 2;</code>
       *
       * <pre>
       * Required for type 1
       * </pre>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string name = 2;</code>
       *
       * <pre>
       * Required for type 1
       * </pre>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 2;</code>
       *
       * <pre>
       * Required for type 1
       * </pre>
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 2;</code>
       *
       * <pre>
       * Required for type 1
       * </pre>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        name_ = value;
        onChanged();
        return this;
      }

      // optional bytes data = 3;
      private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes data = 3;</code>
       *
       * <pre>
       * Required for type 1
       * </pre>
       */
      public boolean hasData() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional bytes data = 3;</code>
       *
       * <pre>
       * Required for type 1
       * </pre>
       */
      public com.google.protobuf.ByteString getData() {
        return data_;
      }
      /**
       * <code>optional bytes data = 3;</code>
       *
       * <pre>
       * Required for type 1
       * </pre>
       */
      public Builder setData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        data_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes data = 3;</code>
       *
       * <pre>
       * Required for type 1
       * </pre>
       */
      public Builder clearData() {
        bitField0_ = (bitField0_ & ~0x00000004);
        data_ = getDefaultInstance().getData();
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:protobuf.Payload)
    }

    static {
      defaultInstance = new Payload(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:protobuf.Payload)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_protobuf_Request_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protobuf_Request_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_protobuf_Header_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protobuf_Header_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_protobuf_Payload_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protobuf_Payload_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013Image.proto\022\010protobuf\"L\n\007Request\022 \n\006he" +
      "ader\030\001 \002(\0132\020.protobuf.Header\022\037\n\004body\030\002 \002" +
      "(\0132\021.protobuf.Payload\"\206\002\n\006Header\0227\n\013requ" +
      "estType\030\001 \001(\0162\034.protobuf.Header.RequestT" +
      "ype:\004read\022<\n\014responseFlag\030\002 \001(\0162\035.protob" +
      "uf.Header.ResponseFlag:\007success\022\024\n\014lastM" +
      "odified\030\003 \001(\003\022\025\n\rcontentLength\030\004 \001(\005\".\n\013" +
      "RequestType\022\010\n\004read\020\000\022\t\n\005write\020\001\022\n\n\006dele" +
      "te\020\002\"(\n\014ResponseFlag\022\013\n\007success\020\000\022\013\n\007fai" +
      "lure\020\001\"3\n\007Payload\022\014\n\004uuid\030\001 \001(\t\022\014\n\004name\030",
      "\002 \001(\t\022\014\n\004data\030\003 \001(\014B2\n\'project1pbversion" +
      ".cmpe275.sjsu.protobufB\007ImagePB"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_protobuf_Request_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_protobuf_Request_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_protobuf_Request_descriptor,
              new java.lang.String[] { "Header", "Body", });
          internal_static_protobuf_Header_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_protobuf_Header_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_protobuf_Header_descriptor,
              new java.lang.String[] { "RequestType", "ResponseFlag", "LastModified", "ContentLength", });
          internal_static_protobuf_Payload_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_protobuf_Payload_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_protobuf_Payload_descriptor,
              new java.lang.String[] { "Uuid", "Name", "Data", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
