# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Image.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='Image.proto',
  package='protobuf',
  serialized_pb='\n\x0bImage.proto\x12\x08protobuf\"K\n\tHeartbeat\x12\x10\n\x08time_ref\x18\x02 \x01(\x03\x12\n\n\x02ip\x18\x03 \x01(\t\x12\x0c\n\x04port\x18\x04 \x01(\x05\x12\x12\n\nloadfactor\x18\x05 \x01(\x01\"L\n\x07Request\x12 \n\x06header\x18\x01 \x02(\x0b\x32\x10.protobuf.Header\x12\x1f\n\x04\x62ody\x18\x02 \x02(\x0b\x32\x11.protobuf.Payload\"\xd9\x01\n\x06Header\x12,\n\nrouting_id\x18\x01 \x01(\x0e\x32\x18.protobuf.Header.Routing\x12\x12\n\noriginator\x18\x02 \x01(\x05\x12\x0b\n\x03tag\x18\x03 \x01(\t\x12\x0c\n\x04time\x18\x04 \x01(\x03\x12*\n\x0bphotoHeader\x18\n \x01(\x0b\x32\x15.protobuf.PhotoHeader\"F\n\x07Routing\x12\x08\n\x04PING\x10\x02\x12\x0e\n\nNAMESPACES\x10\x03\x12\x08\n\x04JOBS\x10\x04\x12\x0b\n\x07REPORTS\x10\n\x12\n\n\x06MANAGE\x10\x64\"7\n\x07Payload\x12,\n\x0cphotoPayload\x18\x04 \x01(\x0b\x32\x16.protobuf.PhotoPayload\"\xa8\x02\n\x0bPhotoHeader\x12<\n\x0brequestType\x18\x01 \x01(\x0e\x32!.protobuf.PhotoHeader.RequestType:\x04read\x12\x41\n\x0cresponseFlag\x18\x02 \x01(\x0e\x32\".protobuf.PhotoHeader.ResponseFlag:\x07success\x12\x14\n\x0clastModified\x18\x03 \x01(\x03\x12\x15\n\rcontentLength\x18\x04 \x01(\x05\x12\x11\n\tentryNode\x18\x05 \x01(\x05\".\n\x0bRequestType\x12\x08\n\x04read\x10\x00\x12\t\n\x05write\x10\x01\x12\n\n\x06\x64\x65lete\x10\x02\"(\n\x0cResponseFlag\x12\x0b\n\x07success\x10\x00\x12\x0b\n\x07\x66\x61ilure\x10\x01\"8\n\x0cPhotoPayload\x12\x0c\n\x04uuid\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x03 \x01(\x0c\x42\x32\n\'project1pbversion.cmpe275.sjsu.protobufB\x07ImagePB')



_HEADER_ROUTING = _descriptor.EnumDescriptor(
  name='Routing',
  full_name='protobuf.Header.Routing',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='PING', index=0, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='NAMESPACES', index=1, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='JOBS', index=2, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='REPORTS', index=3, number=10,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MANAGE', index=4, number=100,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=328,
  serialized_end=398,
)

_PHOTOHEADER_REQUESTTYPE = _descriptor.EnumDescriptor(
  name='RequestType',
  full_name='protobuf.PhotoHeader.RequestType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='read', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='write', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='delete', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=666,
  serialized_end=712,
)

_PHOTOHEADER_RESPONSEFLAG = _descriptor.EnumDescriptor(
  name='ResponseFlag',
  full_name='protobuf.PhotoHeader.ResponseFlag',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='success', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='failure', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=714,
  serialized_end=754,
)


_HEARTBEAT = _descriptor.Descriptor(
  name='Heartbeat',
  full_name='protobuf.Heartbeat',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='time_ref', full_name='protobuf.Heartbeat.time_ref', index=0,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ip', full_name='protobuf.Heartbeat.ip', index=1,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='port', full_name='protobuf.Heartbeat.port', index=2,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='loadfactor', full_name='protobuf.Heartbeat.loadfactor', index=3,
      number=5, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=25,
  serialized_end=100,
)


_REQUEST = _descriptor.Descriptor(
  name='Request',
  full_name='protobuf.Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='protobuf.Request.header', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='body', full_name='protobuf.Request.body', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=102,
  serialized_end=178,
)


_HEADER = _descriptor.Descriptor(
  name='Header',
  full_name='protobuf.Header',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='routing_id', full_name='protobuf.Header.routing_id', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=2,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='originator', full_name='protobuf.Header.originator', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='tag', full_name='protobuf.Header.tag', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='time', full_name='protobuf.Header.time', index=3,
      number=4, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='photoHeader', full_name='protobuf.Header.photoHeader', index=4,
      number=10, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _HEADER_ROUTING,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=181,
  serialized_end=398,
)


_PAYLOAD = _descriptor.Descriptor(
  name='Payload',
  full_name='protobuf.Payload',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='photoPayload', full_name='protobuf.Payload.photoPayload', index=0,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=400,
  serialized_end=455,
)


_PHOTOHEADER = _descriptor.Descriptor(
  name='PhotoHeader',
  full_name='protobuf.PhotoHeader',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='requestType', full_name='protobuf.PhotoHeader.requestType', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='responseFlag', full_name='protobuf.PhotoHeader.responseFlag', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='lastModified', full_name='protobuf.PhotoHeader.lastModified', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='contentLength', full_name='protobuf.PhotoHeader.contentLength', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='entryNode', full_name='protobuf.PhotoHeader.entryNode', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _PHOTOHEADER_REQUESTTYPE,
    _PHOTOHEADER_RESPONSEFLAG,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=458,
  serialized_end=754,
)


_PHOTOPAYLOAD = _descriptor.Descriptor(
  name='PhotoPayload',
  full_name='protobuf.PhotoPayload',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='uuid', full_name='protobuf.PhotoPayload.uuid', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='name', full_name='protobuf.PhotoPayload.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='data', full_name='protobuf.PhotoPayload.data', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=756,
  serialized_end=812,
)

_REQUEST.fields_by_name['header'].message_type = _HEADER
_REQUEST.fields_by_name['body'].message_type = _PAYLOAD
_HEADER.fields_by_name['routing_id'].enum_type = _HEADER_ROUTING
_HEADER.fields_by_name['photoHeader'].message_type = _PHOTOHEADER
_HEADER_ROUTING.containing_type = _HEADER;
_PAYLOAD.fields_by_name['photoPayload'].message_type = _PHOTOPAYLOAD
_PHOTOHEADER.fields_by_name['requestType'].enum_type = _PHOTOHEADER_REQUESTTYPE
_PHOTOHEADER.fields_by_name['responseFlag'].enum_type = _PHOTOHEADER_RESPONSEFLAG
_PHOTOHEADER_REQUESTTYPE.containing_type = _PHOTOHEADER;
_PHOTOHEADER_RESPONSEFLAG.containing_type = _PHOTOHEADER;
DESCRIPTOR.message_types_by_name['Heartbeat'] = _HEARTBEAT
DESCRIPTOR.message_types_by_name['Request'] = _REQUEST
DESCRIPTOR.message_types_by_name['Header'] = _HEADER
DESCRIPTOR.message_types_by_name['Payload'] = _PAYLOAD
DESCRIPTOR.message_types_by_name['PhotoHeader'] = _PHOTOHEADER
DESCRIPTOR.message_types_by_name['PhotoPayload'] = _PHOTOPAYLOAD

class Heartbeat(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _HEARTBEAT

  # @@protoc_insertion_point(class_scope:protobuf.Heartbeat)

class Request(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _REQUEST

  # @@protoc_insertion_point(class_scope:protobuf.Request)

class Header(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _HEADER

  # @@protoc_insertion_point(class_scope:protobuf.Header)

class Payload(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PAYLOAD

  # @@protoc_insertion_point(class_scope:protobuf.Payload)

class PhotoHeader(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PHOTOHEADER

  # @@protoc_insertion_point(class_scope:protobuf.PhotoHeader)

class PhotoPayload(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PHOTOPAYLOAD

  # @@protoc_insertion_point(class_scope:protobuf.PhotoPayload)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), '\n\'project1pbversion.cmpe275.sjsu.protobufB\007ImagePB')
# @@protoc_insertion_point(module_scope)
